<b>Write a function called get_diagonal_sum that takes a square 2D NumPy array as input and returns the sum of its main diagonal elements.</b>

In [8]:
import numpy as np

def get_diagonal_sum(matrix):
    row, col = matrix.shape
    sum = 0
    for i in range(row):
        for j in range(col):
            if i==j:
                sum = sum + matrix[i][j]
    return sum
#     pass

# Test case
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print("Diagonal sum:", get_diagonal_sum(matrix1))


Diagonal sum: 15


<b>Write a function called get_even_rows that takes a 2D NumPy array as input and returns a new array containing only the rows with even indices.</b>

In [19]:
import numpy as np

def get_even_rows(matrix):
    row, col = matrix.shape
    all_rows = np.arange(row)
    return matrix[[i%2==0 for i in all_rows]]
    
    

# Test case
matrix2 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

print("Even rows:")
print(get_even_rows(matrix2))


Even rows:
[[1 2 3]
 [7 8 9]]


<b>Write a function called get_column_average that takes a 2D NumPy array as input and returns a 1D array containing the average value of each column.</b>

In [23]:
import numpy as np

def get_column_average(matrix):
    return np.mean(matrix, axis = 0)


# Test case
matrix3 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print("Column averages:", get_column_average(matrix3))


Column averages: [4. 5. 6.]


<b>Write a function called get_subarray that takes a 2D NumPy array, start_row, end_row, start_col, and end_col as input, and returns the subarray formed by slicing the original array based on the specified indices.<?b>

In [44]:
def sub_array(start_row,end_row,start_col,end_col,mat):
    return mat[start_row:end_row+1,start_col:end_col+1]

In [45]:
sub_array(1,2,1,2,np.arange(9).reshape(3,3))

array([[4, 5],
       [7, 8]])

<b>Write a function called get_last_column that takes a 2D NumPy array as input and returns a 1D array containing the last column of the input array.</b>

In [46]:
def get_last_column(mat):
    return mat[-1]

In [47]:
get_last_column(mat)

array([6, 7, 8])

<b>Write a function called get_even_rows_columns that takes a 2D NumPy array as input and returns a new array containing only the even-indexed rows and columns.</b>

In [48]:
def get_even_rows(mat):
    return mat[::2]

In [49]:
get_even_rows(mat)

array([[0, 1, 2],
       [6, 7, 8]])

<b>Write a function called get_diagonal_elements that takes a square 2D NumPy array as input and returns a 1D array containing its diagonal elements.</b>

In [50]:
def get_diagonal_element(mat):
    return np.diag(mat)

In [51]:
get_diagonal_element(mat)

array([0, 4, 8])

<b>Write a function called get_middle_square that takes a 2D NumPy array as input and returns the square subarray formed by slicing out the middle portion of the array.</b>

In [65]:
def get_middle_square(mat):
    row,col = mat.shape
    return mat[1:row-1,1:col-1]

In [61]:
get_middle_square(mat)

array([[4]])

In [68]:
get_middle_square(np.arange(25).reshape(5,5))

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [70]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

<b>Write a function called reverse_rows that takes a 2D NumPy array as input and returns a new array with the rows reversed.</b>

In [77]:
def reverse_rows(mat):
    mat1 = mat[::-1]
    return mat1

In [78]:
reverse_rows(mat)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [104]:
import random
random.seed(5)
random.random()
random.random()
random.random()

0.7951935655656966

In [106]:
np.random.

In [199]:
l1 = [2,3,4,53,5,67,3,2,3]


In [175]:
random.seed(7)
random.choice(l1)

67

In [220]:
random.seed(7)
random.shuffle(l1)
l1

[2, 5, 3, 67, 3, 3, 4, 53, 2]

In [223]:
random.randint(10,30)

21

In [259]:
# np.random.seed(9)
np.random.rand(2,3)

array([[0.74341313, 0.20103766, 0.90467534],
       [0.47356788, 0.44165318, 0.1360797 ]])

In [302]:
np.random.randint(20,size=(5,5))

array([[ 9,  3,  9, 15, 16],
       [12,  0, 10,  0,  5],
       [ 6,  2, 19, 14, 12],
       [13,  2, 19, 13,  2],
       [10,  1,  1, 17,  6]])

In [281]:
random.random()

0.24066300012702502

In [304]:
np.random.rand(5)

array([0.42436105, 0.39361013, 0.90032563, 0.03580599, 0.45479391])

In [310]:
np.random.randn(2,3)

array([[-0.12237645, -0.58083867, -0.73889782],
       [ 2.48402538,  0.66907458,  1.36927682]])