In [1]:
import numpy as np

In [35]:
np.array(12,dtype='f')

array(12., dtype=float32)

In [8]:
np.asarray(12).dtype

dtype('int32')

In [6]:
np.asanyarray('ab')

array('ab', dtype='<U2')

In [41]:
np.array([ 2, 3.,3+2j])

array([2.+0.j, 3.+0.j, 3.+2.j])

In [42]:


arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [44]:
arr.__array_interface__

{'data': (2732510987136, False),
 'strides': None,
 'descr': [('', '<f8')],
 'typestr': '<f8',
 'shape': (3,),
 'version': 3}

In [45]:
newarr.__array_interface__

{'data': (2732510987616, False),
 'strides': None,
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (3,),
 'version': 3}

In [46]:
new = newarr

In [47]:
new.__array_interface__

{'data': (2732510987616, False),
 'strides': None,
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (3,),
 'version': 3}

In [52]:
import numpy as np

def create_array(rows, columns):
    value = rows*columns
    return np.arange(1,value+1).reshape(rows,columns)
#     pass

# Test cases
rows1, columns1 = 3, 4
rows2, columns2 = 2, 2

array1 = create_array(rows1, columns1)
array2 = create_array(rows2, columns2)

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)


Array 1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array 2:
[[1 2]
 [3 4]]


<b>Create a l1=[1,2,3,4,5] into a 5-d array</b>

In [56]:
np.array([1,2,3,4,5],ndmin = 5)

array([[[[[1, 2, 3, 4, 5]]]]])

In [57]:
np.array([1,2,3,4,5],ndmin = 5).shape

(1, 1, 1, 1, 5)

<b> Create a ndarray and change it's data type</b>

In [58]:
arr = np.array([1,2,3,4,5])

In [59]:
arr.dtype

dtype('int32')

In [60]:
new_arr = arr.astype('f')

In [61]:
new_arr.dtype

dtype('float32')

<b> Create copy and view of an ndarray and then check it's functionality and base</b>

In [62]:
a = np.array([1,2,3,4,5])

In [63]:
b = a.copy()

In [64]:
c = a.view()

In [65]:
b[0]= 25

In [67]:
print(a)
print(b)

[1 2 3 4 5]
[25  2  3  4  5]


In [68]:
c[0]=25

In [69]:
print(a)
print(c)

[25  2  3  4  5]
[25  2  3  4  5]


In [70]:
print(b.base)
print(c.base)

None
[25  2  3  4  5]


<b> Create ndarray using different data structures</b>

In [71]:
np.array([[1,2,3],['a','b','c']])

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U11')

In [73]:
np.array([[1+2j,2+3j,3+6j],['a','b','c']])

array([['(1+2j)', '(2+3j)', '(3+6j)'],
       ['a', 'b', 'c']], dtype='<U64')

In [74]:
np.array([[1+2j,2+3j,3+6j],[4,5,6]])

array([[1.+2.j, 2.+3.j, 3.+6.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [81]:
np.array([[(1,3),(2,6)],[(3,6),(4,9)]])

array([[[1, 3],
        [2, 6]],

       [[3, 6],
        [4, 9]]])

In [82]:
np.array((2,3,4))

array([2, 3, 4])

In [86]:
np.array(((1,2,3),[4,5,6]),ndmin=10)

array([[[[[[[[[[1, 2, 3],
               [4, 5, 6]]]]]]]]]])