In [1]:
import numpy as np

<b>Write a function called generate_random_array that takes rows, columns, lower_limit, and upper_limit as input and returns a random 2D NumPy array of size (rows, columns) with values in the specified range [lower_limit, upper_limit).</b>

In [2]:
def generate_random_array(low,high,row,col):
    return np.random.randint(low=low,high=high,size=(row,col))

In [14]:
generate_random_array(2,10,3,3)

array([[5, 6, 4],
       [8, 4, 7],
       [4, 3, 9]])

<b>Write a function called random_shuffle that takes a 1D NumPy array as input and returns a new array with its elements shuffled randomly.</b>

In [15]:
def random_shuffle(arr):
    np.random.shuffle(arr)
    return arr

In [20]:
random_shuffle([1,2,3,4])

[1, 4, 2, 3]

<b>Write a function called random_sample_mean that takes array_size and sample_size as input, generates a random 1D NumPy array of size array_size, and then calculates and returns the mean of a random sample of size sample_size from the array.</b>

In [59]:
def random_sample_mean(arr_size,sample_size):
    arr = np.random.rand(arr_size)
    sample = np.random.choice(arr,size = sample_size,replace=False)
    return np.mean(sample)

In [61]:
random_sample_mean(100,5)

0.3020381659755807

<b>Write a function called generate_random_matrix that takes size as input and returns a random symmetric matrix of size (size, size).</b>

In [62]:
def generate_random_matrix(size):
    arr = np.random.rand(size,size)
    return np.matrix(arr)

In [65]:
generate_random_matrix(4)

matrix([[0.43235885, 0.28656859, 0.68279892, 0.44021633],
        [0.42461651, 0.47378868, 0.17524966, 0.75676865],
        [0.69381333, 0.97663875, 0.51841369, 0.44126795],
        [0.83805788, 0.14097112, 0.49724033, 0.60350115]])

<b>Write a function called simulate_dice_rolls that takes num_rolls as input and simulates rolling a fair six-sided die num_rolls times. Return a NumPy array containing the results.</b>

In [81]:
def simulate_dice_rolls(num_rolls):
    l1=[]
    for i in range(num_rolls):
        l1.append(np.random.randint(low=0,high=7))
    return l1

In [88]:
simulate_dice_rolls(10)

[5, 6, 1, 5, 4, 2, 6, 6, 6, 4]

<b>Write a function called random_choice_with_replacement that takes a 1D NumPy array and num_samples as input and returns a new array containing a random sample with replacement of size num_samples from the input array.</b>

In [89]:
def random_choice_with_replacement(arr,num_samples):
    return np.random.choice(arr,size=num_samples)
    

In [92]:
random_choice_with_replacement(np.random.rand(10),6)

array([0.03475021, 0.0779602 , 0.31720555, 0.04981761, 0.01196715,
       0.01196715])

<b>Write a function called generate_correlated_data that takes size, mean, covariance_matrix, and random_seed as input and generates random data with the specified mean and covariance matrix. Use random_seed to ensure reproducibility.</b>

In [94]:
import numpy as np

def generate_correlated_data(size, mean, covariance_matrix, random_seed=None):
    """
    Generate random data with specified mean and covariance matrix.

    Parameters:
    - size (int): Number of samples to generate.
    - mean (numpy.ndarray): Mean vector.
    - covariance_matrix (numpy.ndarray): Covariance matrix.
    - random_seed (int or None): Seed for reproducibility. If None, no seed is set.

    Returns:
    - numpy.ndarray: Generated random data.
    """
    # Set the random seed for reproducibility
    if random_seed is not None:
        np.random.seed(random_seed)

    # Generate correlated data using multivariate normal distribution
    generated_data = np.random.multivariate_normal(mean, covariance_matrix, size)

    return generated_data

# Test case
size = 10
mean = np.array([1, 2])
covariance_matrix = np.array([[1, 0.5], [0.5, 2]])
random_seed = 42

generated_data = generate_correlated_data(size, mean, covariance_matrix, random_seed)
print("Generated Data:")
print(generated_data)


Generated Data:
[[ 1.16865045  2.72887797]
 [ 2.62117105  2.36999679]
 [ 0.67426127  1.75839786]
 [ 2.52916684  3.90603269]
 [ 1.17943582  1.17074257]
 [ 0.3533951   1.52263923]
 [-0.43642536  2.98407141]
 [-0.44323683 -0.17592528]
 [ 0.68269794  0.50275982]
 [-0.67808845  1.23494971]]


In [96]:
array_1 = np.array([[1, 2], [3, 4]]) 
array_2 = np.array([[5, 6], [7, 8]]) 
  
array_new = np.concatenate((array_1, array_2), axis=1) 
print(array_new) 

[[1 2 5 6]
 [3 4 7 8]]


In [101]:
ar = np.arange(16).reshape(4,4)

In [102]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
np.diag(ar,k=2)

array([2, 7])

In [107]:
np.diagflat([[1,2,3,],[4,5,6],[7,8,9]])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [115]:
np.mat([[1,3,4],[3,4,7],[1,2,3]]).shape

(3, 3)

In [116]:
import numpy as np
 
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]
